name: any-sync-bundle
services:
  mongo:
    image: docker.io/mongo:4.4
    container_name: any-sync-bundle-mongo
    command:
      - "--replSet"
      - "rs0"
      - "--port"
      - "27017"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/any-sync-bundle/mongo:/data/db
    healthcheck:
      test:
        - CMD-SHELL
        - >
          test $$(mongo --quiet --host 127.0.0.1:27017 --eval
          "try { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]}).ok }
          catch (e) { rs.status().ok }") -eq 1
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    networks:
      - any-sync-bundle

  redis:
    image: docker.io/redis/redis-stack-server:7.4.0-v7
    container_name: any-sync-bundle-redis
    command:
      - "redis-server"
      - "--port"
      - "6379"
      - "--dir"
      - "/data/"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "noeviction"
      - "--protected-mode"
      - "no"
      - "--loadmodule"
      - "/opt/redis-stack/lib/redisbloom.so"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/any-sync-bundle/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s
    networks:
      - any-sync-bundle

  any-sync-bundle:
    image: ghcr.io/grishy/any-sync-bundle:1.3.0-2026-01-31-minimal
    container_name: any-sync-bundle
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "33010:33010"
      - "33020:33020/udp"
    volumes:
      - /DATA/AppData/any-sync-bundle/bundle:/data
    environment:
      ANY_SYNC_BUNDLE_INIT_EXTERNAL_ADDRS: "192.168.1.20"
      ANY_SYNC_BUNDLE_INIT_MONGO_URI: "mongodb://mongo:27017/?replicaSet=rs0"
      ANY_SYNC_BUNDLE_INIT_REDIS_URI: "redis://redis:6379/"
      ANY_SYNC_BUNDLE_INIT_FILENODE_DEFAULT_LIMIT: "2199023255552"
    networks:
      - any-sync-bundle
networks:
  any-sync-bundle:
    name: any-sync-bundle
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  main: any-sync-bundle
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/anytype.png
  index: /
  title:
    custom: Any Sync Bundle