name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1
    container_name: homepage
    ports:
      - 3001:3000
    labels:
      tsdproxy.enable: true
      tsdproxy.name: homepage
    volumes:
      - /DATA/AppData/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
    networks:
      - homepage
      
networks:
  homepage:
    name: homepage
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png
  index: /
  port_map: "3001"
  title:
    custom: Homepage