name: vaultwarden-w
services:
  vaultwarden-w:
    image: vaultwarden/server:1.35.3
    container_name: vaultwarden
    labels:
      tsdproxy.enable: true
      tsdproxy.name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.domain.tld"
    volumes:
      - /DATA/AppData/vaultwarden:/data/
    ports:
      - 10380:80
    networks:
      - vaultwarden
      
networks:
  vaultwarden:
    name: vaultwarden
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: vaultwarden-w
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/vaultwarden.png
  index: /
  port_map: "10380"
  title:
    custom: Vaultwarden
  envs:
    - container: vaultwarden
      name: DOMAIN
      description: Domain URL
      value: https://vw.domain.tld