name: vaultwarden-w
services:
  vaultwarden:
    image: vaultwarden/server:1.35.3
    container_name: vaultwarden
    labels:
      tsdproxy.enable: true
      tsdproxy.name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.seudominio.tld"
    volumes:
      - /DATA/AppData/vaultwarden:/data/
    ports:
      - 10380:80
    networks:
      - vaultwarden
      
networks:
  vaultwarden:
    name: vaultwarden
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: vaultwarden
  port_map: "10380"
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/vaultwarden-light.png
  title:
    custom: Vaultwarden