name: vaultwarden
services:
  vaultwarden:
    image: vaultwarden/server:1.35.3
    container_name: vaultwarden
    labels:
      tsdproxy.enable: true
      tsdproxy.name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.anaconda-amberjack.ts.net"
    volumes:
      - /DATA/AppData/vaultwarden:/data/
    ports:
      - 81:80
    networks:
      - vaultwarden
      
networks:
  vaultwarden:
    name: vaultwarden
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/vaultwarden.png
  index: /
  port_map: "01"
  title:
    custom: Vaultwarden